### PR TITLE
Support multiple api levels

### PR DESCRIPTION
**Pull request by stefan-niedermann**
This PR is the groundwork for #786 

It allows to support multiple API levels.

- [x] Store supported API levels in the database
- [x] Update supported API levels periodically and on Pull 2 Refresh
- [x] [Update supported API levels after each sync](https://github.com/stefan-niedermann/nextcloud-notes/issues/786#issuecomment-613039652)
- [x] [Request supported API levels before adding an account](https://github.com/stefan-niedermann/nextcloud-notes/issues/786#issuecomment-613044301)
- [x] Find highest supported API level with fallback to `0.2`

multi-api-level-support

### CODE REVIEW

**Comment by korelstar** [comment]
If will try to review this if I find enough free time -- it's a quite large PR ...

**Comment by stefan-niedermann** [comment]
Thank you :) Let me know when you find time.

I know it's a pretty big PR, and it will only provide a base from which we can add support for multiple API levels on top.

Though it will not make things easier to review, i will try to keep the PR up to date with the master, so i can work on other issues without risking a huge merge mess in the end.

**Comment by korelstar** [comment]
I see multiple exceptions in logcat:

<details>
<summary>NoClassDefFoundError on every app start</summary>

```
2020-04-21 21:52:31.437 6960-6960/it.niedermann.owncloud.notes.dev I/zygote64: Rejecting re-init on previously-failed class java.lang.Class<androidx.core.view.ViewCompat$2>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/view/View$OnUnhandledKeyEventListener;
2020-04-21 21:52:31.437 6960-6960/it.niedermann.owncloud.notes.dev I/zygote64:     at void androidx.core.view.ViewCompat.setImportantForAccessibility(android.view.View, int) (ViewCompat.java:1091)
2020-04-21 21:52:31.437 6960-6960/it.niedermann.owncloud.notes.dev I/zygote64:     at void androidx.drawerlayout.widget.DrawerLayout.<init>(android.content.Context, android.util.AttributeSet, int) (DrawerLayout.java:336)
2020-04-21 21:52:31.437 6960-6960/it.niedermann.owncloud.notes.dev I/zygote64:     at void androidx.drawerlayout.widget.DrawerLayout.<init>(android.content.Context, android.util.AttributeSet) (DrawerLayout.java:310)
2020-04-21 21:52:31.437 6960-6960/it.niedermann.owncloud.notes.dev I/zygote64:     at java.lang.Object java.lang.reflect.Constructor.newInstance0(java.lang.Object[]) (Constructor.java:-2)
2020-04-21 21:52:31.437 6960-6960/it.niedermann.owncloud.notes.dev I/zygote64:     at java.lang.Object java.lang.reflect.Constructor.newInstance(java.lang.Object[]) (Constructor.java:334)
2020-04-21 21:52:31.437 6960-6960/it.niedermann.owncloud.notes.dev I/zygote64:     at android.view.View android.view.LayoutInflater.createView(java.lang.String, java.lang.String, android.util.AttributeSet) (LayoutInflater.java:647)
2020-04-21 21:52:31.437 6960-6960/it.niedermann.owncloud.notes.dev I/zygote64:     at android.view.View android.view.LayoutInflater.createViewFromTag(android.view.View, java.lang.String, android.content.Context, android.util.AttributeSet, boolean) (LayoutInflater.java:790)
2020-04-21 21:52:31.437 6960-6960/it.niedermann.owncloud.notes.dev I/zygote64:     at android.view.View android.view.LayoutInflater.createViewFromTag(android.view.View, java.lang.String, android.content.Context, android.util.AttributeSet) (LayoutInflater.java:730)
2020-04-21 21:52:31.438 6960-6960/it.niedermann.owncloud.notes.dev I/zygote64:     at android.view.View android.view.LayoutInflater.inflate(org.xmlpull.v1.XmlPullParser, android.view.ViewGroup, boolean) (LayoutInflater.java:492)
2020-04-21 21:52:31.438 6960-6960/it.niedermann.owncloud.notes.dev I/zygote64:     at android.view.View android.view.LayoutInflater.inflate(int, android.view.ViewGroup, boolean) (LayoutInflater.java:423)
2020-04-21 21:52:31.438 6960-6960/it.niedermann.owncloud.notes.dev I/zygote64:     at it.niedermann.owncloud.notes.databinding.DrawerLayoutBinding it.niedermann.owncloud.notes.databinding.DrawerLayoutBinding.inflate(android.view.LayoutInflater, android.view.ViewGroup, boolean) (DrawerLayoutBinding.java:98)
2020-04-21 21:52:31.438 6960-6960/it.niedermann.owncloud.notes.dev I/zygote64:     at it.niedermann.owncloud.notes.databinding.DrawerLayoutBinding it.niedermann.owncloud.notes.databinding.DrawerLayoutBinding.inflate(android.view.LayoutInflater) (DrawerLayoutBinding.java:92)
2020-04-21 21:52:31.438 6960-6960/it.niedermann.owncloud.notes.dev I/zygote64:     at void it.niedermann.owncloud.notes.android.activity.NotesListViewActivity.onCreate(android.os.Bundle) (NotesListViewActivity.java:135)
2020-04-21 21:52:31.438 6960-6960/it.niedermann.owncloud.notes.dev I/zygote64:     at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:6975)
2020-04-21 21:52:31.438 6960-6960/it.niedermann.owncloud.notes.dev I/zygote64:     at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1213)
2020-04-21 21:52:31.438 6960-6960/it.niedermann.owncloud.notes.dev I/zygote64:     at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2770)
2020-04-21 21:52:31.438 6960-6960/it.niedermann.owncloud.notes.dev I/zygote64:     at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2892)
2020-04-21 21:52:31.438 6960-6960/it.niedermann.owncloud.notes.dev I/zygote64:     at void android.app.ActivityThread.-wrap11(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
2020-04-21 21:52:31.438 6960-6960/it.niedermann.owncloud.notes.dev I/zygote64:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1593)
2020-04-21 21:52:31.438 6960-6960/it.niedermann.owncloud.notes.dev I/zygote64:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:105)
2020-04-21 21:52:31.438 6960-6960/it.niedermann.owncloud.notes.dev I/zygote64:     at void android.os.Looper.loop() (Looper.java:164)
2020-04-21 21:52:31.438 6960-6960/it.niedermann.owncloud.notes.dev I/zygote64:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6541)
2020-04-21 21:52:31.438 6960-6960/it.niedermann.owncloud.notes.dev I/zygote64:     at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
2020-04-21 21:52:31.438 6960-6960/it.niedermann.owncloud.notes.dev I/zygote64:     at void com.android.internal.os.Zygote$MethodAndArgsCaller.run() (Zygote.java:240)
2020-04-21 21:52:31.438 6960-6960/it.niedermann.owncloud.notes.dev I/zygote64:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:767)
2020-04-21 21:52:31.438 6960-6960/it.niedermann.owncloud.notes.dev I/zygote64: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.View$OnUnhandledKeyEventListener" on path: DexPathList[[zip file "/data/app/it.niedermann.owncloud.notes.dev-VOErk6KDdo3Yd4lwH3POWQ==/base.apk"],nativeLibraryDirectories=[/data/app/it.niedermann.owncloud.notes.dev-VOErk6KDdo3Yd4lwH3POWQ==/lib/x86_64, /system/lib64, /vendor/lib64]]
2020-04-21 21:52:31.438 6960-6960/it.niedermann.owncloud.notes.dev I/zygote64:     at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:93)
2020-04-21 21:52:31.438 6960-6960/it.niedermann.owncloud.notes.dev I/zygote64:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
2020-04-21 21:52:31.438 6960-6960/it.niedermann.owncloud.notes.dev I/zygote64:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
2020-04-21 21:52:31.438 6960-6960/it.niedermann.owncloud.notes.dev I/zygote64:     at void androidx.core.view.ViewCompat.setImportantForAccessibility(android.view.View, int) (ViewCompat.java:1091)
2020-04-21 21:52:31.438 6960-6960/it.niedermann.owncloud.notes.dev I/zygote64:     at void androidx.drawerlayout.widget.DrawerLayout.<init>(android.content.Context, android.util.AttributeSet, int) (DrawerLayout.java:336)
2020-04-21 21:52:31.438 6960-6960/it.niedermann.owncloud.notes.dev I/zygote64:     at void androidx.drawerlayout.widget.DrawerLayout.<init>(android.content.Context, android.util.AttributeSet) (DrawerLayout.java:310)
2020-04-21 21:52:31.438 6960-6960/it.niedermann.owncloud.notes.dev I/zygote64:     at java.lang.Object java.lang.reflect.Constructor.newInstance0(java.lang.Object[]) (Constructor.java:-2)
2020-04-21 21:52:31.438 6960-6960/it.niedermann.owncloud.notes.dev I/zygote64:     at java.lang.Object java.lang.reflect.Constructor.newInstance(java.lang.Object[]) (Constructor.java:334)
2020-04-21 21:52:31.438 6960-6960/it.niedermann.owncloud.notes.dev I/zygote64:     at android.view.View android.view.LayoutInflater.createView(java.lang.String, java.lang.String, android.util.AttributeSet) (LayoutInflater.java:647)
2020-04-21 21:52:31.438 6960-6960/it.niedermann.owncloud.notes.dev I/zygote64:     at android.view.View android.view.LayoutInflater.createViewFromTag(android.view.View, java.lang.String, android.content.Context, android.util.AttributeSet, boolean) (LayoutInflater.java:790)
2020-04-21 21:52:31.438 6960-6960/it.niedermann.owncloud.notes.dev I/zygote64:     at android.view.View android.view.LayoutInflater.createViewFromTag(android.view.View, java.lang.String, android.content.Context, android.util.AttributeSet) (LayoutInflater.java:730)
2020-04-21 21:52:31.438 6960-6960/it.niedermann.owncloud.notes.dev I/zygote64:     at android.view.View android.view.LayoutInflater.inflate(org.xmlpull.v1.XmlPullParser, android.view.ViewGroup, boolean) (LayoutInflater.java:492)
2020-04-21 21:52:31.438 6960-6960/it.niedermann.owncloud.notes.dev I/zygote64:     at android.view.View android.view.LayoutInflater.inflate(int, android.view.ViewGroup, boolean) (LayoutInflater.java:423)
2020-04-21 21:52:31.438 6960-6960/it.niedermann.owncloud.notes.dev I/zygote64:     at it.niedermann.owncloud.notes.databinding.DrawerLayoutBinding it.niedermann.owncloud.notes.databinding.DrawerLayoutBinding.inflate(android.view.LayoutInflater, android.view.ViewGroup, boolean) (DrawerLayoutBinding.java:98)
2020-04-21 21:52:31.438 6960-6960/it.niedermann.owncloud.notes.dev I/zygote64:     at it.niedermann.owncloud.notes.databinding.DrawerLayoutBinding it.niedermann.owncloud.notes.databinding.DrawerLayoutBinding.inflate(android.view.LayoutInflater) (DrawerLayoutBinding.java:92)
2020-04-21 21:52:31.438 6960-6960/it.niedermann.owncloud.notes.dev I/zygote64:     at void it.niedermann.owncloud.notes.android.activity.NotesListViewActivity.onCreate(android.os.Bundle) (NotesListViewActivity.java:135)
2020-04-21 21:52:31.438 6960-6960/it.niedermann.owncloud.notes.dev I/zygote64:     at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:6975)
2020-04-21 21:52:31.438 6960-6960/it.niedermann.owncloud.notes.dev I/zygote64:     at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1213)
2020-04-21 21:52:31.438 6960-6960/it.niedermann.owncloud.notes.dev I/zygote64:     at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2770)
2020-04-21 21:52:31.438 6960-6960/it.niedermann.owncloud.notes.dev I/zygote64:     at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2892)
2020-04-21 21:52:31.438 6960-6960/it.niedermann.owncloud.notes.dev I/zygote64:     at void android.app.ActivityThread.-wrap11(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
2020-04-21 21:52:31.438 6960-6960/it.niedermann.owncloud.notes.dev I/zygote64:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1593)
2020-04-21 21:52:31.438 6960-6960/it.niedermann.owncloud.notes.dev I/zygote64:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:105)
2020-04-21 21:52:31.438 6960-6960/it.niedermann.owncloud.notes.dev I/zygote64:     at void android.os.Looper.loop() (Looper.java:164)
2020-04-21 21:52:31.438 6960-6960/it.niedermann.owncloud.notes.dev I/zygote64:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6541)
2020-04-21 21:52:31.438 6960-6960/it.niedermann.owncloud.notes.dev I/zygote64:     at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
2020-04-21 21:52:31.438 6960-6960/it.niedermann.owncloud.notes.dev I/zygote64:     at void com.android.internal.os.Zygote$MethodAndArgsCaller.run() (Zygote.java:240)
2020-04-21 21:52:31.438 6960-6960/it.niedermann.owncloud.notes.dev I/zygote64:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:767)
```

</details>


<details>
<summary>JSONException and NullPointerException by CapabilitiesClient</summary>

```
2020-04-21 21:52:33.426 6960-7006/it.niedermann.owncloud.notes.dev V/CapabilitiesClient: NextcloudRequest: NextcloudRequest(method=GET, header={}, parameter={format=json}, requestBody=null, url=/ocs/v2.php/cloud/capabilities, token=3df5d3dcdab84a2c987f8dad923d79fc, packageName=null, accountName=test@nc.korelstar.de, bodyAsStream=null, followRedirects=false)
2020-04-21 21:52:33.431 6960-7006/it.niedermann.owncloud.notes.dev W/System.err: org.json.JSONException: No value for notes
2020-04-21 21:52:33.461 6960-7006/it.niedermann.owncloud.notes.dev W/System.err:     at org.json.JSONObject.get(JSONObject.java:392)
2020-04-21 21:52:33.461 6960-7006/it.niedermann.owncloud.notes.dev W/System.err:     at org.json.JSONObject.getJSONObject(JSONObject.java:612)
2020-04-21 21:52:33.461 6960-7006/it.niedermann.owncloud.notes.dev W/System.err:     at it.niedermann.owncloud.notes.model.Capabilities.<init>(Capabilities.java:53)
2020-04-21 21:52:33.462 6960-7006/it.niedermann.owncloud.notes.dev W/System.err:     at it.niedermann.owncloud.notes.persistence.CapabilitiesClient.getCapabilities(CapabilitiesClient.java:61)
2020-04-21 21:52:33.462 6960-7006/it.niedermann.owncloud.notes.dev W/System.err:     at it.niedermann.owncloud.notes.persistence.CapabilitiesWorker.doWork(CapabilitiesWorker.java:48)
2020-04-21 21:52:33.462 6960-7006/it.niedermann.owncloud.notes.dev W/System.err:     at androidx.work.Worker$1.run(Worker.java:85)
2020-04-21 21:52:33.462 6960-7006/it.niedermann.owncloud.notes.dev W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
2020-04-21 21:52:33.462 6960-7006/it.niedermann.owncloud.notes.dev W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
2020-04-21 21:52:33.462 6960-7006/it.niedermann.owncloud.notes.dev W/System.err:     at java.lang.Thread.run(Thread.java:764)
2020-04-21 21:52:33.462 6960-7006/it.niedermann.owncloud.notes.dev W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'char java.lang.String.charAt(int)' on a null object reference
2020-04-21 21:52:33.462 6960-7006/it.niedermann.owncloud.notes.dev W/System.err:     at android.graphics.Color.parseColor(Color.java:1384)
2020-04-21 21:52:33.462 6960-7006/it.niedermann.owncloud.notes.dev W/System.err:     at it.niedermann.owncloud.notes.persistence.NotesDatabase.updateBrand(NotesDatabase.java:742)
2020-04-21 21:52:33.462 6960-7006/it.niedermann.owncloud.notes.dev W/System.err:     at it.niedermann.owncloud.notes.persistence.CapabilitiesWorker.doWork(CapabilitiesWorker.java:49)
2020-04-21 21:52:33.462 6960-7006/it.niedermann.owncloud.notes.dev W/System.err:     at androidx.work.Worker$1.run(Worker.java:85)
2020-04-21 21:52:33.462 6960-7006/it.niedermann.owncloud.notes.dev W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
2020-04-21 21:52:33.462 6960-7006/it.niedermann.owncloud.notes.dev W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
2020-04-21 21:52:33.462 6960-7006/it.niedermann.owncloud.notes.dev W/System.err:     at java.lang.Thread.run(Thread.java:764)
2020-04-21 21:52:33.475 6960-6984/it.niedermann.owncloud.notes.dev I/WM-WorkerWrapper: Worker result FAILURE for Work [ id=0fd0744d-7006-4b1e-a40a-3aa34b760f9e, tags={ it.niedermann.owncloud.notes.persistence.CapabilitiesWorker } ]
```

</details>

... and I think there were more on the first start.


As a result, I'm getting

```
I/NotesClient: apiVersion is null, using NotesClient_0_2
```

although I have installed current master of notes web app.

Today, I have not the time anymore to debug, but maybe the exceptions will help you.

File: app/src/main/java/it/niedermann/owncloud/notes/model/LocalAccount.java [hunk 1]
```diff
@@ -59,6 +77,54 @@ public void setModified(long modified) {
...
+                this.preferredApiVersion = null;
+                return;
+            }
+            JSONArray versionsArray = new JSONArray(availableApiVersions);
+            Collection<ApiVersion> supportedApiVersions = new ArrayList<>(versionsArray.length());
+            for (int i = 0; i < versionsArray.length(); i++) {
+                ApiVersion parsedApiVersion = ApiVersion.of(versionsArray.getString(i));
+                for (ApiVersion temp : NotesClient.SUPPORTED_API_VERSIONS) {
+                    if (temp.compareTo(parsedApiVersion) == 0) {
+                        supportedApiVersions.add(parsedApiVersion);
```
Comment (korelstar) [inline app/src/main/java/it/niedermann/owncloud/notes/model/LocalAccount.java:100]: `compareTo` is implemented with an `equal`-like functionality. This is not the intended way to get the supported API versions. You should only check the major version of the API.

Example: The server provides "1.4, 2.1". Then, you chose "1.4", because you only support major version "1" but not "2". Due to backward/forward compatibility, your implementation for "1.0" will work on the "1.4" API endpoint.

Example 2: The server provides "0.2, 1.4" and your app has implemented the API for "0.2" and "1.7". Then, you should still chose "1.4" (since you support major version "1"). Requests will still work, but you must be aware, that the result may miss some fields that were not defined in "1.4" but in "1.7".

(API `0.2` is a special case, since the major version of `0.2` is `0.2` and not `0`.)

Comment (stefan-niedermann) [reply app/src/main/java/it/niedermann/owncloud/notes/model/LocalAccount.java:100]: `compareTo` now only compares the `major`-version of the API.

**Comment by stefan-niedermann** [comment]
> NoClassDefFoundError on every app start

Tried it on an API level `15` and `29` device but did not get this Exception. Which Android Studio version do you use?

> although I have installed current master of notes web app.

Well, at least the fallback seems to work :D When do you plan to release version `3.3` of the server app?

**Comment by korelstar** [comment]
I'm using AndroidStudio 3.6.3 with Android Emulator 30.0.5 and Android 8.0 / API 26 revision 14.

Strange, I can't reproduce the exceptions, today. Before, AndroidStudio updated the build tools. :confused: 

But it still uses the fallback to `NotesClient_0_2`.

Before releasing version 3.3, I planned to finish the documentation. Unfortunately, I'm running low on time, currently. So I don't know exactly, when it will be finished. It would be good to have a reference implementation though, in order to proof that we are using a working approach.

**Comment by korelstar** [comment]
Aaah, no. The exceptions still occurs, I've just overseen the filter set in Logcat ... :-|

**Comment by korelstar** [comment]
I fixed the second exception and the API detection.

**Comment by beatbrot** [comment]
I'm really sorry but I guess I currently don't have the time to review such a large PR :/ Hope you understand!

File: app/src/main/java/it/niedermann/owncloud/notes/persistence/NoteServerSyncHelper.java [hunk 2]
```diff
@@ -92,7 +92,7 @@ public void onReceive(Context context, Intent intent) {
     // current state of the synchronization
     private final Map<String, Boolean> syncActive = new HashMap<>();
     private final Map<String, Boolean> syncScheduled = new HashMap<>();
-    private final NotesClient notesClient;
+    private final Map<String, NotesClient> notesClients = new HashMap<>();
```
Comment (korelstar) [inline app/src/main/java/it/niedermann/owncloud/notes/persistence/NoteServerSyncHelper.java:95]: I suggest to remove this "cache" for NotesClients. NotesClients are state-less (there is no object variable), so the only thing that is won with this cache is omitting a single object creation on each server request. However, since the constructor is very simple, we are not saving a significant amount of time.

The drawback of this cache is, that it makes the code rather complicated and you have to ensure, that you are not using an outdated client (i.e. with an old API version), which is error-prone.

Therefore, I strongly suggest to remove this, since it's drawbacks are dominating.

Comment (stefan-niedermann) [reply app/src/main/java/it/niedermann/owncloud/notes/persistence/NoteServerSyncHelper.java]: Done

File: app/src/main/java/it/niedermann/owncloud/notes/android/activity/NotesListViewActivity.java [hunk 3]
```diff
@@ -308,6 +319,18 @@ else if (dy < 0)
                     Log.i(TAG, "Clearing Glide disk cache");
                     Glide.get(getApplicationContext()).clearDiskCache();
                 }).start();
+                new Thread(() -> {
```
[the remark this answers is not in the document]
Comment (stefan-niedermann) [reply app/src/main/java/it/niedermann/owncloud/notes/android/activity/NotesListViewActivity.java:322]: > clearing both Glide caches

According to the Glide docs, the memory cache has to be cleared on the `UIThread` while the disk cache has to be cleared on a `WorkerThread`.

In the long term i will try to detect an avatar change using `HEAD`-requests and `ETags`, but this is out of scope for this PR. Until this works properly i want to keep the "clear Glide cache"-stuff as close as possible to the Pull 2 Refresh action.

Also: Glide is only used for the avatar in the navigation drawer and for the "Move note to another account"-stuff. Both aren't triggered, when synchronizing on Pull 2 Refresh. Therefore i don't see any reason why it should *not* run in parallel.

---

But i agree, that we should run "Refresh Capabilities" → "Synchronize" sequentially. I adjusted that.
